In [10]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [19]:
stock_data

        종목코드   수정주가        날짜
0     098120   2142  20110404
1     131100    NaN       NaN
2     009520   6360  20110404
3     095570    NaN       NaN
4     006840  21226  20110404
...      ...    ...       ...
2609     NaN    NaN       NaN
2610     NaN    NaN       NaN
2611     NaN    NaN       NaN
2612     NaN    NaN       NaN
2613     NaN    NaN       NaN

[2614 rows x 3 columns]

In [18]:
stocks_now = pd.read_csv('stocks.csv', encoding='euckr')
stock_codes = stocks_now['단축코드']
indexes = [319, 569, 816, 1063, 1307, 1555, 1803, 2045, 2287, 2536, 2782]

columns = ['종목코드', '수정주가', '날짜']
stock_data = pd.DataFrame([], columns = columns, 
                           index=range(len(stock_codes))    
)

for ind in indexes[:1]:

    stock_data = pd.DataFrame([], columns = columns, index=range(len(stock_codes)))
    for i, code in enumerate(stock_codes[:10]):
        print(code, 'scraping...')
        url =  f"https://fchart.stock.naver.com/sise.nhn?symbol={code}&timeframe=day&count=3000&requestType=0"
        res = requests.get(url)
        soup = BeautifulSoup(res.text, 'html.parser')
        stocks = soup.select('item')
        
        try:
            stock_date = stocks[ind - 3000]['data'].split('|')[0]
            stock_end = stocks[ind - 3000]['data'].split('|')[-2]
        except:
            stock_date = np.nan
            stock_end = np.nan
        stock_code = code
        stock_data.iloc[i] = [stock_code, stock_end, stock_date]
    
    stock_data.to_csv(f'{ind}.csv')

098120 scraping...
131100 scraping...
009520 scraping...
095570 scraping...
006840 scraping...
282330 scraping...
027410 scraping...
138930 scraping...
001465 scraping...
001460 scraping...

In [32]:
investment = 100000000
buy_money = {}

for i in range(2011, 2022):
    globals()[f'df{i}'] =  pd.read_csv(f'.\\주가총액csv\\{i}.csv', encoding='euckr')    
    globals()[f'buy_num{i}'] = {}
    buy = 0
    profit = 0
    
    
    # 2011년일 경우 사기만 한다.
    if i == 2011:
        for name in globals()[f'names{i}']:
            df = globals()[f'df{i}']
            closing = int(df[df.종목명 == f'{name}']['종가'])
            investment_each = investment // len(globals()[f'names{i}']) 
            rest_each = int(investment_each % closing)

            buy_money[f'{name}'] = int((investment_each // closing) * closing)
            globals()[f'buy_num{i}'][f'{name}'] = int(investment_each // int(closing))
            print(name, f'지금가격 {closing}원 ', buy_num2011[f'{name}'] , '개 구매')# '투자금', buy_money[f'{name}'], '원')
            profit = 0

    else:
        # 전년도에 샀던 주식들을 오늘의 가격으로 판매
        
        for nameb in globals()[f'names{i-1}']:
            df = globals()[f'df{i}']
            dfb = globals()[f'df{i-1}']
            closingn = int(df[df.종목명 == f'{nameb}']['종가'])
            closingb = int(dfb[dfb.종목명 == f'{nameb}']['종가'])
            profit_each = (int(globals()[f'buy_num{i-1}'][f'{nameb}'])) * (closingn - closingb)
            profit += profit_each
            print(nameb, f'지금가격 {closingn}원 작년가격 {closingb}원', globals()[f'buy_num{i-1}'][f'{nameb}'], '개 판매', f' 1년 수익: {profit_each}원')
        before_profit = investment
        investment += profit
        print('-'*20)    
        
        # 판매후 변화한 금액을 기준으로 새로운 종목들을 구매
        
        for name in globals()[f'names{i}']:

            df = globals()[f'df{i}']
            dfb = globals()[f'df{i-1}']
            closing = int(df[df.종목명 == f'{name}']['종가'])
            investment_each = investment // len(globals()[f'names{i}']) 

            globals()[f'buy_num{i}'][f'{name}'] = int(investment_each // closing)
            print(name, closing,'원', globals()[f'buy_num{i}'][f'{name}'], '개 구매')# '투자금', globals()[f'buy_num{i}'][f'{name}'] * int(closing), '원')
            buy +=  globals()[f'buy_num{i}'][f'{name}'] * closing

    if investment <= 0:
        break

    if i == 2011:
        profit_rate = 0
    else:
        profit_rate = (investment - before_profit) / before_profit * 100

    
    print(f'{i}년 총 자산 : {investment}원, 수익 : {profit}원, 수익률 : {round(profit_rate, 1)}%')
    print('='*80)

KeyError: 'names2011'

In [31]:
globals()
df2011

NameError: name 'df2011' is not defined